version: "3.3"
services:
    db:
        container_name: bierlijst_db
        image: mongo
        restart: always
        env_file:
            - .env
        ports:
            - "27017:27017"
    backend:
        container_name: bierlijst_backend
        depends_on:
            - db
        env_file:
            - .env
        build:
            context: '.'
            dockerfile: './backend/backend.dockerfile'
        ports:
            - "8001:8001"